name       : perl-text-csv-xs
version    : 1.35
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.35.tgz : 2b4f111e9486b230b02bfabbbf50c453f959d18ec17351a930e41f0959b358b7
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Text::CSV_XS - comma-separated values manipulation routines
description: |
    Text::CSV_XS provides facilities for the composition and decomposition
    of comma-separated values.  An instance of the Text::CSV_XS class can
    combine fields into a CSV string and parse a CSV string into fields.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
